name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: '10'
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'pnpm'
    - name: Run pnpm install
      run: pnpm install
    - name: Run prettier
      run: pnpm pretty-check
    - name: Run eslint
      run: pnpm lint

